### PR TITLE
Justin/landing

### LINKED ISSUE #9: [Feature] Create landing page
### Description

Lay out and build the landing page that users will see when they visit the PDF site. This should give a quick intro on what PDF is about, how to sign up, logistics (location and schedule), and a short section on "Who runs PDF?" aka ScottyLabs.

See https://wdw.scottylabs.org/

### Designs

Pending from Design Committee

### PR DESCRIPTION
**Pull request by justinzhang**
# Description

Behold the landing page. Pls help with the style, I do not web develop.

Closes #9 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] I looked at it and deemed it semi-acceptable

### CODE REVIEW

**Comment by justinzhang** [comment]
Also could I get a higher res asset of the pdf logo

**Comment by gramliu** [comment]
image

Could we center these? Also maybe set the width of the text here to be something like `50%` of the width. It looks a bit awkward since the content is spread out a bit too wide

**Comment by justinzhang** [comment]
> image
> 
> Could we center these? Also maybe set the width of the text here to be something like `50%` of the width. It looks a bit awkward since the content is spread out a bit too wide

Hmm that's strange, I can't seem to replicate it on my end, whether on local or on deploy preview. Resizing windows works properly for me as well. I'll try to make it less wide.

**Comment by gramliu** [comment]
Yeah, you might need to set the width to 50% only for large viewports and keep it as-is for smaller viewports like mobile

**Comment by justinzhang** [comment]
woops broken on mobile

**Comment by gramliu** [comment]
I think the extra margins are a bit weird on mobile.

**Comment by justinzhang** [comment]
ok that did not work lol

**Comment by justinzhang** [comment]
@gramliu fixed the padding on mobile. However, could not add padding for the title and the text under it since it takes the class from docusaurus, so I can't query viewport easily it seems

**Comment by gramliu** [comment]
Awesome, thanks! I made a PR into this branch with some changes as well to improve responsiveness on mobile screens and make our layout a bit more concise

**Pull request merged**
